### ISSUE TITLE
5.5.1 doesn't run on Linux

### ISSUE THREAD

**Issue by RenaKunisaki** [moderngl/moderngl#327]
**Description**

Running on Arch Linux AMD64, installed from pip, fails with error:

```Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    import moderngl_window as mglw
  File "/mnt/guilmon/home/rena/projects/python-glsl/moderngl_window/moderngl_window/__init__.py", line 10, in <module>
    from moderngl_window.context.base import WindowConfig, BaseWindow
  File "/mnt/guilmon/home/rena/projects/python-glsl/moderngl_window/moderngl_window/context/base/__init__.py", line 3, in <module>
    from moderngl_window.context.base.window import BaseWindow
  File "/mnt/guilmon/home/rena/projects/python-glsl/moderngl_window/moderngl_window/context/base/window.py", line 5, in <module>
    import moderngl
  File "/usr/lib/python3.7/site-packages/moderngl/__init__.py", line 22, in <module>
    from . import new
ImportError: cannot import name 'new' from 'moderngl' (/usr/lib/python3.7/site-packages/moderngl/__init__.py)
```

5.5.0 worked OK.

**Version info**
```

python -m moderngl
/usr/bin/python: Error while finding module specification for 'moderngl.__main__' (ImportError: cannot import name 'new' from 'moderngl' (/usr/lib/python3.7/site-packages/moderngl/__init__.py))

```

**Comment by einarf** [comment]
Is this related to packages in setup.py again?

```
packages=['moderngl', 'moderngl.program_members'],
```

**Comment by einarf** [comment]
5.5.2 is now released to solve this problem
