### ISSUE TITLE
moderngl.error.Error: cannot create program

### ISSUE THREAD

**Issue by lochuynh1989** [moderngl/moderngl#331]
**Description**
I got this error when trying to do headless rendering on server.

```
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
  File "/usr/local/lib/python3.6/dist-packages/moderngl/context.py", line 835, in program
    varyings
moderngl.error.Error: cannot create program
```

**My setup**

```bash
pip install moderngl
apt-get install mesa-common-dev
apt-get install mesa-utils
apt-get install xvfb
export DISPLAY=:99.0
Xvfb :99 -screen 0 640x480x24 &
```

**Proof of code**

```python
import moderngl
ctx = moderngl.create_standalone_context()
prog = ctx.program(
    vertex_shader='''
        #version 330
        in vec2 in_vert;
        in vec3 in_color;
        out vec3 v_color;
        void main() {
            v_color = in_color;
            gl_Position = vec4(in_vert, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330
        in vec3 v_color;
        out vec3 f_color;
        void main() {
            f_color = v_color;
        }
    ''',
)
```

**Expected behavior**

Should raise no error.

**Version info**

```
moderngl 5.5.2
--------------
vendor:
renderer:
version:
python: 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
platform: linux
code: 0
```

**Comment by einarf** [comment]
AFAIK: To enable context version chech you need to pass in the required min version

```
moderngl.create_context(require=330)
```

Seeing `code: 0` in the version info is not a good sign.

**Comment by lochuynh1989** [comment]
I got this message following your suggestion:
ValueError: Requested OpenGL version 330, got version 0

**Comment by cprogrammer1994** [comment]
The `cannot create program` means that the function `glCreateProgram()` returns `0`

I know the latest mesa & Xvfb work fine with moderngl.

What is your mesa version?

**Comment by cprogrammer1994** [comment]
I run the code in docker `ubuntu:18.04` and got no errors.

Here is a mesa version that work out of the box.

```
root@4c8f4f1afb86:/# glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.0.2
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.1 Mesa 19.0.2
OpenGL shading language version string: 1.40
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by lochuynh1989** [comment]
I ran glxinfo | grep version. It returned nothing.
glxgears got a Segmentation fault (core dumped).

Maybe I should consider using docker.

**Comment by cprogrammer1994** [comment]
it can be a driver issue,
docker just helps you create some sort of independent environment.
the code should be able to run without docker.
I used docker to test ubuntu:18.04's mesa version without adding any extra PPAs.

**Comment by cprogrammer1994** [comment]
Please reopen if it is still not working
