### ISSUE TITLE
Error while trying to run a program that uses moderngl

### ISSUE THREAD

**Issue by newtonsart** [moderngl/moderngl#393]
python -m moderngl
```
moderngl 5.6.0
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
version: 3.3 (Core Profile) Mesa 20.0.4
python: 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]
platform: linux
code: 330
```

[Here](https://github.com/Leterax/Visualization) is the repo of the program i tried to run, but it happens with some of them, I know that i cant use shaders but those programs doesnt require them.

python Voronoi/main.py  
```
2020-04-14 01:23:08,253 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.pyglet.Window
Traceback (most recent call last):
  File "Voronoi/main.py", line 47, in <module>
    moderngl_window.run_window_config(Voronoi)
  File "/home/lolart/.local/lib/python3.8/site-packages/moderngl_window/__init__.py", line 176, in run_window_config
    window = window_cls(
  File "/home/lolart/.local/lib/python3.8/site-packages/moderngl_window/context/pyglet/window.py", line 48, in __init__
    self._window = PygletWrapper(
  File "/home/lolart/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/lolart/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 590, in __init__
    config = screen.get_best_config(config)
  File "/home/lolart/.local/lib/python3.8/site-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```

**Comment by einarf** [comment]
In most cases this is due to multisampling : https://github.com/Leterax/Visualization/blob/4ec2db8463d01d2d17ccd54f01afd9d69be14e4b/Voronoi/main.py#L14

Disable by setting to 0. Most of those examples use moderngl-window, so you can pass in samples param : `python Voronoi/main.py --samples 0`

**Comment by einarf** [comment]
Resovled on discord. There are several issues in the linked repo and the owner has been notified!
