### ISSUE TITLE
Buffer access from a separate Thread

### ISSUE THREAD

**Issue by Leterax** [moderngl/moderngl#398]
**Description**

Not entirely sure if this is a bug, but trying to read a buffer from another thread will throw the error `moderngl.error.Error: cannot map the buffer`. Slight side note, writing to the buffer fails silently, seemingly doing nothing.

full traceback:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\threading.py", line 948, in _bootstrap_inner
    self.run()
  File "M:/Code/Voxels/multithreaded_generation/bug_report.py", line 19, in run
    data = self.buffer.read()
  File "C:\Users\user\.virtualenvs\VoxelTrace\lib\site-packages\moderngl\buffer.py", line 101, in read
    return self.mglo.read(size, offset)
moderngl.error.Error: cannot map the buffer
```
**Proof of code**

```py
import struct

import moderngl
import numpy as np
from moderngl_window.opengl.vao import VAO
import moderngl_window as mglw
import threading


class MyThread(threading.Thread):
    def __init__(self, buffer):
        super().__init__()

        self.buffer = buffer
        self.start()

    def run(self):
        while True:
            data = self.buffer.read()
            print(struct.unpack("f" * 128, data))


class BugReport(mglw.WindowConfig):
    # moderngl_window settings
    gl_version = (3, 3)
    title = "bug_report"
    # app settings
    N = 128

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)

        # load programs
        self.program = self.ctx.program(
            vertex_shader="""
            #version 330
            in vec2 in_position;
            
            void main() {
                gl_Position = vec4(in_position, 0., 1.0);
            }""",
            fragment_shader="""
            #version 330
            out vec4 fragColor;

            void main() {
                fragColor = vec4(0., 1., 0., 1.);
            }""",
        )

        # create a buffer and a VAO
        positions = np.random.random((self.N, 2)).astype("f4")
        positions -= 0.5
        positions *= 2.0
        buffer_01 = self.ctx.buffer(positions)

        self.vao = VAO(name="vao")
        self.vao.buffer(buffer_01, "2f", ["in_position"])

        t = MyThread(buffer_01)

    def render(self, time: float, frame_time: float) -> None:
        self.ctx.clear(51 / 255, 51 / 255, 51 / 255)

        # render the result
        self.vao.render(self.program, mode=moderngl.POINTS)


if __name__ == "__main__":
    mglw.run_window_config(BugReport)
```

**Expected behavior**

I would have expected the buffer to be read into `data`.

**Version info**
```
moderngl 5.6.0
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 1070/PCIe/SSE2
version: 3.3.0 NVIDIA 445.87
python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
platform: win32
code: 330
```

**Comment by Leterax** [comment]
if this is intentional, see this as a feature request ;)
