### ISSUE TITLE
Bad error message when vertex attribute name is invalid

### ISSUE THREAD

**Issue by lordmauve** [moderngl/moderngl#402]
**Description**

In `context.vertex_array()`, error messages when a vertex attribute is invalid are very unhelpful:

```
Traceback (most recent call last):
  File "examples/tanks/tanks.py", line 14, in <module>
    'sand_base_2',
  File "/home/mauve/dev/wasabi2d/wasabi2d/layers.py", line 344, in add_tile_map
    tiles = TileMap(self, *args, **kwargs)
  File "/home/mauve/dev/wasabi2d/wasabi2d/primitives/tile_map.py", line 176, in __init__
    [(self._tilemgr.verts, *TileManager.MGL_DTYPE)]
  File "/home/mauve/dev/wasabi2d/venv/lib/python3.7/site-packages/moderngl/context.py", line 944, in vertex_array
    return self._vertex_array(*args, **kwargs)
  File "/home/mauve/dev/wasabi2d/venv/lib/python3.7/site-packages/moderngl/context.py", line 974, in _vertex_array
    index_element_size, skip_errors)
moderngl.error.Error: content[0][3] must be an attribute not NoneType
```

This occurs when creating a vertex array with code like:

```python
vao = self.layer.ctx.vertex_array(
    someprog,
    [
        (vertbuf, '2i4 u2', 'in_vert', 'in_tilemap_block'),
    ]
)
```

and `in_tilemap_block` is not referenced by the shader. (Actually it is, but I commented out the use of it and my driver compiles it out completely).

**Expected behavior**

I'd like this error message to read something like

```
moderngl.error.Error: 'in_tilemap_block' is not a vertex attribute, or has been compiled out during shader compilation
```

**Version info**

```
moderngl 5.6.0
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
version: 4.5 (Core Profile) Mesa 18.0.5
python: 3.7.2 (default, Aug 14 2019, 19:21:48) 
[GCC 5.4.0 20160609]
platform: linux
code: 450
```

**Comment by lordmauve** [comment]
Even better would be if I could ask moderngl to swallow the error, maybe by appending a question mark?

```python
vao = self.layer.ctx.vertex_array(
    someprog,
    [
        (vertbuf, '2i4 u2', 'in_vert', 'in_tilemap_block?'),
    ]
)
```

**Comment by einarf** [comment]
The first one is at least simple enough to fix and is already on the list.

**Comment by einarf** [comment]
This might even be better.
> ValueError: Program doesn't have attribute 'color' or it has been removed during shader compilation. Available attributes: ('pos', 'velocity')

**Comment by szabolcsdombi** [comment]
This will be improved in #561
