### ISSUE TITLE
Inadequate Error message when an np array does not support contiguous read-only data

### ISSUE THREAD

**Issue by Leterax** [moderngl/moderngl#406]
**Description**

When an np array does not support simple buffers (contiguous read-only data) the resulting error message is inadequate:

`SystemError: <method 'buffer' of 'mgl.Context' objects> returned NULL without setting an error`

**Expected behavior**

A nicer error message explaining the problem.

**Version info**

```
moderngl 5.6.0
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 1070/PCIe/SSE2
version: 3.3.0 NVIDIA 445.87
python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
platform: win32
code: 330

```

**Comment by cprogrammer1994** [comment]
I think `PyBuffer_Release` may clear the error set by `MGLError_Set`
I see no return 0 without setting an error (except for arguments where error is set by the python c api)

https://github.com/moderngl/moderngl/blob/master/moderngl/src/Buffer.cpp#L3

**Comment by einarf** [comment]
I was just looking at that code and had the exact same thought.

**Comment by cprogrammer1994** [comment]
```py
>>> import numpy as np
>>> x = np.array([1.0, 2.0, 3.0, 4.0], 'f4')
>>> import moderngl as mgl
>>> ctx = mgl.create_context(standalone=True)
>>> ctx.buffer(x[::2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python38\lib\site-packages\moderngl\context.py", line 781, in buffer
    res.mglo, res._size, res._glo = self.mglo.buffer(data, reserve, dynamic)
SystemError: <method 'buffer' of 'mgl.Context' objects> returned NULL without setting an error
```

**Comment by einarf** [comment]
Fixed. Just letting the raw errors from `PyObject_GetBuffer` propagate up instead of using a custom error.

```python
>>> import numpy as np
>>> x = np.array([1.0, 2.0, 3.0, 4.0], 'f4')
>>> import moderngl as mgl
>>> ctx = mgl.create_context(standalone=True)
>>> ctx.buffer(x[::2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python38\lib\site-packages\moderngl\context.py", line 781, in buffer
    res.mglo, res._size, res._glo = self.mglo.buffer(data, reserve, dynamic)
ValueError: ndarray is not C-contiguous
```
