### ISSUE TITLE
Uniform that seems active not found in Program dictionary

### ISSUE THREAD

**Issue by infowantstobeseen** [moderngl/moderngl#412]
**Description**

A uniform in my fragment shader, though used, is not found in the Program dictionary so when I try to retrieve it, a KeyError is thrown.

**Proof of code**

The [shaders and the moderngl (w/ moderngl-window) code upload](https://github.com/moderngl/moderngl/files/5127571/rays_bad.zip). Key part is here:

```py
class RayViewer(moderngl_window.WindowConfig):
    resource_dir = pathlib.Path(__file__).parent

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self._vao = quad_fs(normals=False, uvs=False)
        self._prog = self.load_program(vertex_shader  = "cast_bad.vert",
                                       fragment_shader= "cast_bad.frag")
        # Error here
        self._eye = self._prog["eye"]
```

The error says the uniform cannot be found

```
Traceback (most recent call last):
  File ".\rays_bad.py", line 36, in <module>
    moderngl_window.run_window_config(RayViewer)
  File "D:\Development\envs\gfx\lib\site-packages\moderngl_window\__init__.py", line 193, in run_window_config
    window.config = config_cls(ctx=window.ctx, wnd=window, timer=timer)
  File ".\rays_bad.py", line 21, in __init__
    self._eye = self._prog["eye"]
  File "D:\Development\envs\gfx\lib\site-packages\moderngl\program.py", line 73, in __getitem__
    return self._members[key]
KeyError: 'eye'
```

**Expected behavior**

The uniform is being used in the fragment shader, so should be active.

**Version info**

```
moderngl 5.6.1
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 1080/PCIe/SSE2
version: 3.3.0 NVIDIA 445.87
python: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
platform: win32
code: 330
```

**Comment by einarf** [comment]
```glsl
#version 330

out vec4 fragColor;
uniform vec3 eye;

void main()
{
        vec3 f = vec3(1., 0., 0.) - eye;
        fragColor = vec4(0., 0., 0., 1.);
}
```

The glsl compiler is smart and removes the uniform because it doesn't affect what is written to `fragColor`.

**Comment by infowantstobeseen** [comment]
Ah, premature (but understandable) optimization being the root of all evil and such. I misunderstood how uniform dependency and thus elimination was determined. 

Thanks and apologies for the report.

**Comment by einarf** [comment]
I've added a task to include information about this in docs.
