### ISSUE TITLE
Mac m1 error

### ISSUE THREAD

**Issue by Viksis** [moderngl/moderngl#489]
Hello, I tried a simple test.py app with this code:

```py
# test.py
import moderngl_window as mglw

class Test(mglw.WindowConfig):
    gl_version = (3, 3)

    def render(self, time, frametime):
        self.ctx.clear(1.0, 0.0, 0.0, 0.0)

Test.run()
```

But i always get an error no matter what python version i tried:
```
Traceback (most recent call last):
  File "/Users/pepsi/python/pygl/main.py", line 2, in <module>
    import moderngl_window as mglw
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/__init__.py", line 15, in <module>
    from moderngl_window.context.base import WindowConfig, BaseWindow
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/context/base/__init__.py", line 2, in <module>
    from moderngl_window.context.base.window import BaseWindow, WindowConfig  # noqa
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/context/base/window.py", line 12, in <module>
    from moderngl_window import resources
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/resources/__init__.py", line 8, in <module>
    from moderngl_window.resources.programs import programs  # noqa
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/resources/programs.py", line 2, in <module>
    from moderngl_window.resources.base import BaseRegistry
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/resources/base.py", line 11, in <module>
    from moderngl_window.meta.base import ResourceDescription
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/meta/__init__.py", line 2, in <module>
    from .texture import TextureDescription  # noqa
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/moderngl_window/meta/texture.py", line 2, in <module>
    from PIL.Image import Image
  File "/Users/pepsi/Library/Python/3.8/lib/python/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/pepsi/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): no suitable image found.  Did find:
        /Users/pepsi/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wpepsig architecture
        /Users/pepsi/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wpepsig architecture
```

**Comment by einarf** [comment]
ah right. You would have to build moderngl locally on M1 currently. Will be resolved in 5.7. If you have xcode installed it should be fairly simple.

**Comment by Viksis** [comment]
Now i have this:

`Traceback (most recent call last):
  File "common.py", line 24, in <module>
    def get_context(require=330) -> moderngl.Context:
AttributeError: module 'moderngl' has no attribute 'Context'`

**Comment by einarf** [comment]
Right. This would probably apply to the glcontext pacakge as  well.

I'm sorry about this, but none of our contrubutor have an M1 or have the funds to buy one. We'll just have to build a wheel and hope that it works.

**Comment by Viksis** [comment]
:(

**Comment by einarf** [comment]
Don't get me wrong. You can easily compile glcontext as well

**Comment by Viksis** [comment]
OK, but it's very sad that a project like this literally ignored and some shitty python library is way more sponsored.

**Comment by Viksis** [comment]
OK, but it's very sad that a project like this literally ignored and some shitty python library is way more sponsored.

**Comment by einarf** [comment]
We'll try to get new wheels out very soon

**Comment by szabolcsdombi** [comment]
does this mean the cibuidweels producing invalid wheels, or the more likely case that our code does not run despite compiled for m1?

**Comment by einarf** [comment]
No. It should build the right wheels. We just need to set it up properly and make a release

**Comment by matanster** [comment]
([M1 on AWS](https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-ec2-m1-mac-instances-macos/), in case its anywhere near practical)

**Comment by einarf** [comment]
The 2.6.4 wheels should now be present on PyPI
