### ISSUE TITLE
vertex_array creation fails

### ISSUE THREAD

**Issue by mcs32** [moderngl/moderngl#514]
version : 5.6.4

I am trying to test the following simple example wherein I pass something to the vertex shader and read its output to print.

```python
import moderngl
import numpy as np
import struct

vertex_shader_source = '''
    #version 330
    
    in vec3 attPosition;
    out vec2 varScreenCoord;
    
    void main ()
    {
        varScreenCoord = vec2(1.0, 1.5);
    }
'''

ctx = moderngl.create_standalone_context()
prog = ctx.program(vertex_shader=vertex_shader_source, varyings=['varScreenCoord'])

# input
verts = np.array([[0.0, 0.0, 0.0],
                  [1.0,  0.0, 0.0],
                  [1.0,  1.0, 0.0]], dtype='f4')
verts_buf = ctx.buffer(verts.tobytes())

# output
n, c = verts.shape
varScreenCoord = np.zeros((n, c-1)).astype(np.float32)
varScreenCoord_buf = ctx.buffer(varScreenCoord.tobytes())

vao = ctx.vertex_array(prog, content=[
    (verts_buf, '3f', 'attPosition')
])

vao.transform(varScreenCoord_buf, vertices=n)

data = struct.unpack("{}f".format(n*2), varScreenCoord_buf.read())
for i in range(0, n*2):
    print("value = {}".format(data[i]))
```

I get the following error when I run this
```
Traceback (most recent call last):
  File "/somepath/moderngl_sample.py", line 32, in <module>
    vao = ctx.vertex_array(prog, content=[
  File "/somepath/lib/python3.9/site-packages/moderngl/context.py", line 1140, in vertex_array
    return self._vertex_array(*args, **kwargs)
  File "/somepath/lib/python3.9/site-packages/moderngl/context.py", line 1169, in _vertex_array
    res.mglo, res._glo = self.mglo.vertex_array(program.mglo, content, index_buffer_mglo,
moderngl.error.Error: content[0][2] must be an attribute not NoneType
```

I have checked the buffer format [here](https://moderngl.readthedocs.io/en/latest/topics/buffer_format.html#example-of-simple-usage) and it seems to be correct. [This](https://github.com/moderngl/moderngl/issues/402) indicates that the name might not be referenced in the shader, but my shader clearly has that vertex attribute named `attPosition`.

What could be causing this issue? 

Thank you.

**Comment by mcs32** [comment]
After using the `attPosition` value in the shader, this issue was fixed. For example, the shader looks as follows now
```glsl
    #version 330
    
    in vec3 attPosition;
    out vec2 varScreenCoord;
    
    void main ()
    {
        varScreenCoord = vec2(1.0, 1.5) * attPosition.xy;
    }
```

**Comment by einarf** [comment]
The compiler/linking stage will purge unused members/code in most drivers. This is perfectly normal. I think 5.7 / master branch have some better error messages. There is also a suggestion supporting optional attributes with a ?` suffix for cases like this.

**Comment by mcs32** [comment]
Thank you! will check it out.
