### ISSUE TITLE
All examples fail: No module named 'moderngl_window'

### ISSUE THREAD

**Issue by yurivict** [moderngl/moderngl#548]
```
$ python3.9 julia_fractal.py
Traceback (most recent call last):
  File "/usr/ports/graphics/py-moderngl/work-py39/moderngl-5.7.4/examples/julia_fractal.py", line 4, in <module>
    from ported._example import Example
  File "/usr/ports/graphics/py-moderngl/work-py39/moderngl-5.7.4/examples/ported/_example.py", line 3, in <module>
    import moderngl_window as mglw
ModuleNotFoundError: No module named 'moderngl_window'
```

Version: 5.7.4
Python-3.9
FreeBSD 13.1

**Comment by yurivict** [comment]
The package moderngl-window was missing.
