### ISSUE TITLE
Can't create shader program from a python thread

### ISSUE THREAD

**Issue by space928** [moderngl/moderngl#623]
**Description**

I need to be able to use ModernGL asynchronously for my project. When attempting to create a shader program (`ctx.program(fragment_shader=...)`) from a different thread ModernGL throws an error with the message `cannot create program`. This occurs even with GC disabled.

**Proof of code**

Apologies for the verbosity...
```py
#  Copyright (c) 2023 Thomas Mathieson.
#  Distributed under the terms of the MIT license.

import threading
import logging
import time

import moderngl
import numpy as np


class SSVRenderOpenGL:
    """
    A rendering backend for SSV based on OpenGL
    """

    def __init__(self, resolution):
        self.resolution = resolution
        self.__create_context()
        self.start_time = time.time()

    def __create_context(self):
        """
        Creates an OpenGL context and a framebuffer.
        """
        self.ctx = moderngl.create_context(standalone=True)

        # To use moderngl with threading we need call the garbage collector manually
        self.ctx.gc_mode = None

        resolution = (min(self.resolution[0], self.ctx.info["GL_MAX_VIEWPORT_DIMS"][0]),
                      min(self.resolution[1], self.ctx.info["GL_MAX_VIEWPORT_DIMS"][1]))
        self.fbo = self.ctx.simple_framebuffer(resolution, components=4)
        self.fbo.use()

    def log_context_info(self, full=False):
        """
        Logs the OpenGL information to the console for debugging.
        :param full: whether to log *all* of the OpenGL context information (including extensions)
        """
        print(f"Got OpenGL context:\n"
              f"\tGL_VENDOR={self.ctx.info['GL_VENDOR']}\n"
              f"\tGL_RENDERER={self.ctx.info['GL_RENDERER']}\n"
              f"\tGL_VERSION={self.ctx.info['GL_VERSION']}")
        if full:
            from pprint import pformat
            info = pformat(self.ctx.info, indent=4)
            print(f"Full info: \n{info}")
            extensions = pformat(self.ctx.extensions, indent=4)
            print(f"GL Extensions: \n{extensions}")

    def register_shader(self):
        ...

    def dbg_render_test(self):
        # Create a vertex buffer
        vertices = np.array([
            # X      Y      R    G    B
            -1.0, -1.0, 1.0, 0.0, 0.0,
            1.0, -1.0, 0.0, 1.0, 0.0,
            0.0, 1.0, 0.0, 0.0, 1.0],
            dtype='f4',
        )

        self.log_context_info()
        prog = self.ctx.program(vertex_shader="""
        #version 330
        in vec2 in_vert;
        in vec3 in_color;
        out vec3 color;
        out vec2 position;
        void main() {
            gl_Position = vec4(in_vert, 0.0, 1.0);
            color = in_color;
            position = in_vert*0.5+0.5;
        }
        """,
                                fragment_shader="""
        #version 330
        out vec4 fragColor;
        in vec3 color;
        in vec2 position;

        uniform vec2 iResolution;
        uniform float iTime;

        float amod(float x, float y)
        {
            return x - y * floor(x/y);
        }

        vec4 mainImage(in vec2 fragCoord)
        {
            // Normalized pixel coordinates (from 0 to 1)
            vec2 uv = fragCoord/iResolution.xy;

            float coord = floor(fragCoord.x) + floor(fragCoord.y/10.) + floor(iTime);
            //vec3 col = vec3(amod(coord, 16.)>=8.?1.:0., amod(coord, 32.)>=16.?1.:0., amod(coord, 64.)>=32.?1.:0.);
            //col = amod(coord, 128.)>64.?(col*0.3333+.3333):col;

            vec3 col = vec3(amod(coord, 64.) >= 56. ? 1. : 0.,
                            amod(coord + 16., 64.) >= 56. ? 1. : 0.,
                            amod(coord + 32., 64.) >= 56. ? 1. : 0.);
            col += amod(coord + 48., 64.) >= 56. ? 1. : 0.;
            col = amod(coord, 128.) > 64. ? (col * 0.3333 + .3333) : col;

            // Output to screen
            return vec4(col,1.0);
        }

        void main() {
            fragColor = mainImage(position * iResolution) + vec4(color, 1.0)*0.01;
            //fragColor = vec4(color, 1.0);
        }
        """)

        # Set uniforms
        prog["iResolution"].value = self.resolution
        prog["iTime"].value = time.time() - self.start_time

        # Assign buffers and render
        vao = self.ctx.simple_vertex_array(prog, self.ctx.buffer(vertices), 'in_vert', 'in_color')
        vao.render(mode=moderngl.TRIANGLES)

    def get_frame(self):
        """
        Gets the current contents of the frame buffer as a byte array.
        :return: the contents of the frame buffer as a bytearray in the ``RGBA`` format.
        """
        return self.fbo.read(components=4)


renderer = SSVRenderOpenGL((640, 480))


def render_loop(exit_flag):
    target_framerate = 60
    last_frame_time = time.time()
    timeout = 0
    delta_time = 1 / target_framerate
    while not exit_flag.wait(timeout=timeout):
        renderer.dbg_render_test()

        current_time = time.time()
        delta_time = current_time - last_frame_time
        timeout = max(1 / target_framerate - delta_time, 0)
        last_frame_time = current_time
        break


def run():
    exit_flag = threading.Event()
    thread = threading.Thread(target=render_loop, args=(exit_flag,))

    # render_loop(exit_flag)
    thread.start()


run()


```

**Expected behavior**

Note, that this example doesn't save it's output anywhere, but it should run without error.

**Actual behaviour**
```
Got OpenGL context:
	GL_VENDOR=NVIDIA Corporation
	GL_RENDERER=NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
	GL_VERSION=3.3.0 NVIDIA 537.42
Exception in thread Thread-1 (render_loop):
Traceback (most recent call last):
  File "C:\Users\####\.conda\envs\IndProject\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\####\.conda\envs\IndProject\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\####\test-threading.py", line 142, in render_loop
    renderer.dbg_render_test()
  File "D:\Users\####\test-threading.py", line 66, in dbg_render_test
    prog = self.ctx.program(vertex_shader="""
  File "C:\Users\####\.conda\envs\IndProject\lib\site-packages\moderngl\__init__.py", line 1939, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: cannot create program
```

**Version info**

```
moderngl 5.8.2
--------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
version: 3.3.0 NVIDIA 537.42
python: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
platform: win32
code: 330
```

**Comment by szabolcsdombi** [comment]
if you are using threads you must handle opengl context switching,
the opengl context can be current only in one thread.
there are some methods (begin, end) in glcontext, but not sure if you need those.
with raw api call it looks like the following:

```py
wglMakeCurrent(...)
# can call moderngl code here
wglMakeCurrent(NULL, NULL)
```

check the docs what happens when another thread calls `wglMakeCurrent` while the context is active in some other thread. you may have to add some mutexes.

also please do keep in mind that due to the Python GIL you have no real benefits of using threads unless those are idling on IO without the GIL being held.

the OpenGL driver is not multithreaded so whatever you do with it on multiple threads it will land in sync calls one after the other.

PS:

If you want to put rendering on a dedicated thread, that may be totally reasonable and you should make the opengl context current there and leave it like that.

**Comment by space928** [comment]
Hi, thanks for the help, I've ended up using a dedicated render process which works quite nicely. I'll close this issue as resolved.
