### ISSUE TITLE
x11 error

### ISSUE THREAD

**Issue by Kohki0401** [moderngl/moderngl#674]
Hello 
When I use moderngl, below error happened. it seems to be from openGL context:

I tried to use python3.8, and python3.9 

-------------------------------------------------------------- log ---------------------------------------------------------------
Traceback (most recent call last):
  File "/home/datasynthesizer/Documents/IA_data/InstantAvatar/scripts/visualize-SMPL.py", line 101, in <module>
    viewer = HeadlessRenderer()
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/aitviewer/headless.py", line 21, in __init__
    super().__init__(**kwargs)
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/aitviewer/viewer.py", line 127, in __init__
    self.window = base_window_cls(
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/moderngl_window/context/headless/window.py", line 24, in __init__
    self.init_mgl_context()
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/moderngl_window/context/headless/window.py", line 40, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/moderngl/__init__.py", line 1986, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/datasynthesizer/miniconda3/envs/ROMP/lib/python3.9/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) cannot create context

And my env is below
-------------------------------------------------------------- env ---------------------------------------------------------------
Ubuntu20.04 ( distribution is bookworm/sid, I confirmed)
miniconda env
x11
I tried "xeyes" and "glxgears" and these worked on terminal

glxinfo | grep "OpenGL version"
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1

I tried moderngl/examples/headless/moderngl_logo.py on my env.
It worked by changing python3 version from py3.8 to py3.9. but there are still same error...

**Comment by compik710** [comment]
Correct operation of the code due to a change in Python version may be due to installing different versions of the ModernGL library for each version of Python. Check the versions of ModernGL for each version of Python.

Also try replacing the line 
```py
ctx = moderngl.create_standalone_context()
```
with
```py
ctx = moderngl.create_context(standalone=True, backend='egl')
```
