### ISSUE TITLE
Ubuntu 22.04 Exception:(standalone) cannot create context

### ISSUE THREAD

**Issue by GISerCHAO** [moderngl/moderngl#675]
### code
import moderngl
ctx = moderngl.create_context()
print(ctx)
### terminal output
(Viewer3D) (base) hyq@hyq-virtual-machine:~/3DViewer-master/3DViewer-master$ /home/hyq/anaconda3/envs/Viewer3D/bin/python /home/hyq/3DViewer-master/3DViewer-master/test.py
Traceback (most recent call last):
  File "/home/hyq/3DViewer-master/3DViewer-master/test.py", line 2, in <module>
    ctx = moderngl.create_context()
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (detect) glXGetCurrentContext: cannot detect OpenGL context
### code
import moderngl
ctx = moderngl.get_context()
buf = ctx.buffer(b"Hello World!")  # allocated on the GPU
buf.read()
### terminal output
(Viewer3D) (base) hyq@hyq-virtual-machine:~/3DViewer-master/3DViewer-master$ /home/hyq/anaconda3/envs/Viewer3D/bin/python /home/hyq/3DViewer-master/3DViewer-master/test.py
Traceback (most recent call last):
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/_moderngl.py", line 217, in __init__
    raise RuntimeError("Cannot detect window with OpenGL support")
RuntimeError: Cannot detect window with OpenGL support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyq/3DViewer-master/3DViewer-master/test.py", line 2, in <module>
    ctx = moderngl.get_context()
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/moderngl/__init__.py", line 1981, in get_context
    init_context()
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/moderngl/__init__.py", line 1963, in init_context
    loader = DefaultLoader()
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/_moderngl.py", line 226, in __init__
    raise RuntimeError("Cannot detect window with OpenGL support")
RuntimeError: Cannot detect window with OpenGL support
### issue
My computer has a dual-boot setup with Ubuntu and Windows. The code runs without any problems on Windows 11, but no matter what I do, it doesn't work on Ubuntu. I've tried many methods, but none of them have worked. What could be the issue? If anyone can tell me, I would be extremely grateful.

**Comment by GISerCHAO** [comment]
@szabolcsdombi sorry, it doesn't work for me. Its output as follow:
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/hyq/work/3DViewer/test.py", line 2, in <module>
    ctx = moderngl.create_context(standalone=True)
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/hyq/anaconda3/envs/Viewer3D/lib/python3.9/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) cannot create context

**Comment by compik710** [comment]
I can assume that you are having problems installing Ubuntu correctly. Giving an error like this makes me doubt that Ubuntu has access to the GPU at all.

Have you tried running the `glxgears` command in the console?

**Comment by GISerCHAO** [comment]
> I can assume that you are having problems installing Ubuntu correctly. Giving an error like this makes me doubt that Ubuntu has access to the GPU at all.
> 
> Have you tried running the `glxgears` command in the console?

I have already tried the 'glxgears' command, and it runs without errors. Moreover, I have tried many Windows computers with Ubuntu, including those with GPUs and those without GPUs, but none of them can run the test code for moderngl properly; they all report the same error.

**Comment by GISerCHAO** [comment]
> > I can assume that you are having problems installing Ubuntu correctly. Giving an error like this makes me doubt that Ubuntu has access to the GPU at all.
> > Have you tried running the `glxgears` command in the console?
> 
> I have already tried the 'glxgears' command, and it runs without errors. Moreover, I have tried many Windows computers with Ubuntu, including those with GPUs and those without GPUs, but none of them can run the test code for moderngl properly; they all report the same error.

The test code only runs properly on Windows; switching to Ubuntu results in an error.

**Comment by Ammareli** [comment]
Have anyone Resolved the above Issue

**Comment by szabolcsdombi** [comment]
@Ammareli try

```py
import moderngl
ctx = moderngl.create_context(standalone=True)
print(ctx)
```

**Comment by meghbhalerao** [comment]
Hi, I am facing the same errror. @szabolcsdombi when I try your recommended test  - 
```python
import moderngl
ctx = moderngl.create_context(standalone=True)
print(ctx)
```


I get the following output - 
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[1], line 2
      1 import moderngl
----> 2 ctx = moderngl.create_context(standalone=True)
      3 print(ctx)

File ~/anaconda3/envs/fix_aitviewer/lib/python3.10/site-packages/moderngl/__init__.py:2174, in create_context(require, standalone, share, **settings)
   2171 from moderngl import mgl  # type: ignore
   2173 ctx = Context.__new__(Context)
-> 2174 ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
   2175 ctx._info = None
   2176 ctx._extensions = None

File ~/anaconda3/envs/fix_aitviewer/lib/python3.10/site-packages/glcontext/__init__.py:90, in _x11.<locals>.create(*args, **kwargs)
     88 _apply_env_var(kwargs, 'libx11', 'GLCONTEXT_LINUX_LIBX11')
     89 kwargs = _strip_kwargs(kwargs, ['glversion', 'mode', 'libgl', 'libx11'])
---> 90 return x11.create_context(**kwargs)

Exception: (standalone) cannot create context
```


Could you please recommend a fix? Thanks for your time and help!

Megh

**Comment by meghbhalerao** [comment]
@Ammareli did you fix the above issue? Thanks!
