### ISSUE TITLE
Exception: requested device index 0, but found 0 devices

### ISSUE THREAD

**Issue by Zhangkaiwen2001** [moderngl/moderngl#683]
code:
import moderngl

if __name__ == "__main__":
    mgl_ctx = moderngl.create_context(standalone=True, backend='egl', device_index=0)

error:
Traceback (most recent call last):
  File "/data/zhangkaiwen/ivid-main/test.py", line 4, in <module>
    mgl_ctx = moderngl.create_context(standalone=True, backend='egl', device_index=0, libgl='libGL.so.1')
  File "/data/zhangkaiwen/anaconda3/envs/I2V_attack/lib/python3.9/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/data/zhangkaiwen/anaconda3/envs/I2V_attack/lib/python3.9/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: requested device index 0, but found 0 devices

what should i do?

**Comment by crowwater** [comment]
Have you solved this problem? I also meet it. Please tell me how to solve it, thanks

**Comment by szabolcsdombi** [comment]
this should be a driver issue, please try to run standard egl examples first.
once you can run EGL examples, moderngl will work too.
