### ISSUE TITLE
ValueError: Requested OpenGL version 330, got version 0

### ISSUE THREAD

**Issue by maximus-sallam** [moderngl/moderngl#711]
I created this OpenGL test file:
```
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ cat test.cpp
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <iostream>

int main() {
    // Initialize GLFW
    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW" << std::endl;
        return -1;
    }

    // Set GLFW OpenGL version (3.3 core profile)
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    // Create a windowed mode window and its OpenGL context
    GLFWwindow* window = glfwCreateWindow(640, 480, "OpenGL Test", nullptr, nullptr);
    if (!window) {
        std::cerr << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return -1;
    }

    // Make the window's context current
    glfwMakeContextCurrent(window);

    // Initialize GLEW
    glewExperimental = GL_TRUE;
    if (glewInit() != GLEW_OK) {
        std::cerr << "Failed to initialize GLEW" << std::endl;
        glfwDestroyWindow(window);
        glfwTerminate();
        return -1;
    }

    // Print OpenGL version
    std::cout << "OpenGL Version: " << glGetString(GL_VERSION) << std::endl;
    std::cout << "GLSL Version: " << glGetString(GL_SHADING_LANGUAGE_VERSION) << std::endl;
    std::cout << "Vendor: " << glGetString(GL_VENDOR) << std::endl;
    std::cout << "Renderer: " << glGetString(GL_RENDERER) << std::endl;

    // Clean up and exit
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```
I then compiled and ran it:
```
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ g++ -o test test.cpp -I/opt/homebrew/include -L/opt/homebrew/lib -lGLEW -lglfw -framework OpenGL
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ ./test
OpenGL Version: 4.1 Metal - 89.3
GLSL Version: 4.10
Vendor: Apple
Renderer: Apple M3 Max
```
And I have the pip3 packages installed:
```
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ pip3 list
Package          Version
---------------- -----------
astar            0.99
contourpy        1.3.0
cycler           0.12.1
fonttools        4.54.1
glcontext        3.0.0
kiwisolver       1.4.7
matplotlib       3.9.2
moderngl         5.12.0
numpy            2.1.3
packaging        24.2
pillow           11.0.0
pip              24.3.1
pygame           2.6.1
PyOpenGL         3.1.7
pyparsing        3.2.0
pypresence       4.3.0
python-dateutil  2.9.0.post0
setuptools       74.1.2
six              1.16.0
sortedcontainers 2.4.0
wheel            0.44.0
```
But I'm getting this error:
```
>>> moderngl.create_context(debug=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/moderngl/__init__.py", line 2262, in create_context
    raise ValueError("Requested OpenGL version {0}, got version {1}".format(require, ctx.version_code))
ValueError: Requested OpenGL version 330, got version 0
```

**Comment by maximus-sallam** [comment]
As an update, I created this Python script to test OpenGL:
```
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ cat test.py
import glfw
import moderngl

def error_callback(error, description):
    print(f"GLFW Error ({error}): {description.decode('utf-8')}")

# Set the error callback
glfw.set_error_callback(error_callback)

# Initialize the glfw library
if not glfw.init():
    raise Exception("Failed to initialize GLFW")

# Set window hints to force OpenGL 3.3 core profile
glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, glfw.TRUE)

# Create a windowed mode window and its OpenGL context
window = glfw.create_window(800, 600, "ModernGL Context Test", None, None)
if not window:
    glfw.terminate()
    raise Exception("Failed to create GLFW window")

print(f"GLFW Version: {glfw.get_version_string()}")

# Make the window's context current
glfw.make_context_current(window)

# Create a ModernGL context
ctx = moderngl.create_context(debug=True)

# Print some OpenGL information
print("OpenGL Version:", ctx.version_code)
print("Vendor:", ctx.info["GL_VENDOR"])
print("Renderer:", ctx.info["GL_RENDERER"])
print("GLSL Version:", ctx.info["GL_VERSION"])

# Clean up
glfw.terminate()
```
And here are the results from running this test:
```
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ python3 test.py
GLFW Version: b'3.4.0 Cocoa NSGL Null EGL OSMesa monotonic dynamic'
OpenGL Version: 410
Vendor: Apple
Renderer: Apple M3 Max
GLSL Version: 4.1 Metal - 89.3
```

**Comment by maximus-sallam** [comment]
After installing glfw via brew, this is the new error:
```
┌──(maximus💀MaxBook-Pro)-[~/Downloads]
└─$ python3
Python 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 16.0.0 (clang-1600.0.26.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import moderngl
>>> ctx = moderngl.create_context(debug=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/opt/homebrew/lib/python3.10/site-packages/glcontext/__init__.py", line 100, in create
    return darwin.create_context(**_strip_kwargs(kwargs, ['mode']))
Exception: cannot detect OpenGL context
```
